throwErrorOnExtraParameters: true

templates:
  report: !template
    reportTemplate: pdfReport.jrxml

    attributes:
      # Global variables
      placeholderlabel: !string {}
      
      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      competentauthority: !string {} 
      
      # Variables for footer
      # Variables for title page
      municipality: !string {}
      municipalitylabel: !string {}
      federalmunicipalitynumber: !string {}
      cadastre: !string {}
      report_title: !string {}
      extractsubtitlelabel: !string {}
      propertylabel: !string {}
      propertynumber: !string {}
      propertytype: !string {}
      propertyarealabel: !string {}
      propertyarea: !string {}
      EGRIDlabel: !string {}
      EGRIDnumber: !string {}
      creationdatelabel: !string {}
      extractcreationdate: !string {}
      extractoperatorlabel: !string {}
      certificationlabel: !string {}

      # Variables for TOC
      # Variables for topic page
      legendlabel: !string {}
      completlegendlabel: !string {} 
      legalbaseslabel: !string {} 
      legalprovisionslabel: !string {} 
      referenceslabel: !string {} 
      competentauthoritylabel: !string {} 

      map: !map
        maxDpi: 400
        width: 493
        height: 280
        
      datasource: !datasource
        attributes:
          topic_title: !string {}
          #~ topic_text: !string {}
          table: !table {}
          
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: map}
    - !createDataSource
      reportTemplate: table.jrxml
      reportKey: reportTemplate
      processors:
        - !prepareTable {}
    tableData: jrDataSource